### PR TITLE
(build) fix deps, ci and lint

### PR DESCRIPTION
**Pull request by christian-hawk**
Basically:

- refactoring code to fit eslint (changed `var` variables, used `path.join` to concatenate)
- added and configured`lint-staged` so lint will run only for staged commit files on `pre-commit-hook`
- moved `husky` config out from `package.json`
- added `eslint-standard-config` module to be run extending standardJS (@kdhttps let me know if you are not all right with this)
- minor updated dependencies
- added eslint security and scanjs for security scanning as "info warning" for now
Commits are self-explanatory and isolated :)

### CODE REVIEW

**Comment by jgomer2001** [comment]
`request` was changed in preference for  `got` right? 
isn't passport-openidconnect dependant on `request`. How's that handled now? is there any impact

**Comment by christian-hawk** [comment]
> `request` was changed in preference for `got` right?
> isn't passport-openidconnect dependant on `request`. How's that handled now? is there any impact

@jgomer2001 actually not yet, got is used only on integrations tests for now. We should check `passport-openidconnect` and all other deps before the switch, also the code impact isn't small thou.

**Review by kdhttps — CHANGES_REQUESTED** [review]
@christian-hawk its returning some warning

```
$ npm run lint

> passport@4.3.6 lint /home/kd/Documents/GLUU/gluu-passport
> eslint 'server/**/*.js' 'test/**/*.js' 'config/**/*.js'

(node:13181) [ESLINT_LEGACY_ECMAFEATURES] DeprecationWarning: The 'ecmaFeatures' config file property is deprecated and has no effect. (found in ".eslintrc.json")

/home/kd/Documents/GLUU/gluu-passport/server/app.js
  63:3   warning  The function setTimeout can be unsafe  scanjs-rules/call_setTimeout
  71:23  warning  Found non-literal argument in require  security/detect-non-literal-require

.
.
.

✖ 48 problems (0 errors, 48 warnings)

```

**Comment by christian-hawk** [comment]
@kdhttps fixed the ecmaFeatures.
The other warnings are related to security and it's implemented for warnings only for now, we should do a milestone to fix them and then turn the switch to breaking CI (error instead of warning).

**Review by kdhttps — APPROVED** [review]
> The other warnings are related to security and it's implemented for warnings only for now, we should do a milestone to fix them and then turn the switch to breaking CI (error instead of warning).

Milestone means to cover it in new issue or next release?

**Comment by christian-hawk** [comment]
@kdhttps yes mate. We should plan how to do it.

**Pull request merged**
