### PR TITLE
Patch : Fetch values from envs for production.js

### LINKED ISSUE #374: Add support to configure production.js params using envs
Currently, some configs are hardcoded in production.js. 

[support issue](https://support.gluu.org/authentication/10081/oxpassport-too-many-restarts-due-to-unhealthy-liveness-probe/)

Also, In gluu-passport, there are multiple sources for configs so we should make it into one. I'll create separate issue for this.

### PR DESCRIPTION
**Pull request by kdhttps**
close #374

### CODE REVIEW

**Review by christian-hawk — CHANGES_REQUESTED** [review]
As is a new feature, it should be merged to `master`, as explained in rocket chat.

**Comment by kdhttps** [comment]
> As is a new feature, it should be merged to master, as explained in rocket chat.

@christian-hawk sure mate but as I understand the issue we have to deliver the patch ASAP. I will make another PR for master after this.

**Comment by moabu** [comment]
yes this is needed @christian-hawk .

**Comment by kdhttps** [comment]
Closing. Working on new PR as we decided to make patch with "REMOVE Rate-limit"

**Pull request closed without merging**
