### PR TITLE
refactor: remove unused openid-client module

### LINKED ISSUE #165: Remove unused openid-client dependency
Currently we are not using `openid-client` deps so we can remove it from dependencies

### PR DESCRIPTION
**Pull request by christian-hawk**
closes #165

### CODE REVIEW

**Comment by christian-hawk** [comment]
run tests

**Comment by christian-hawk** [comment]
run tests

**Comment by christian-hawk** [comment]
run tests

**Comment by christian-hawk** [comment]
run tests

**Comment by christian-hawk** [comment]
run tests

**Review by kdhttps — CHANGES_REQUESTED** [review]
Mate, I think we can also remove this line https://github.com/GluuFederation/gluu-passport/blob/82cc3a65f346eaed8ca24fc04b95c48c4719b6e1/server/providers.js#L8

**Review by kdhttps — APPROVED** [review]

**Pull request merged**
