### PR TITLE
fix(app-factory.js): fix location undefine and req.flash function problem

### LINKED ISSUE #170: TypeError: Cannot read property 'location' of undefined
Getting this problem, when we redirect back to passport with `access_denied` response from external OP

```
TypeError: Cannot read property 'location' of undefined
    at redirect (/home/kd/Documents/GLUU/gluu-passport/node_modules/express/lib/response.js:926:18)
    at /home/kd/Documents/GLUU/gluu-passport/server/app-factory.js:47:7
    at Layer.handle_error (/home/kd/Documents/GLUU/gluu-passport/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/home/kd/Documents/GLUU/gluu-passport/node_modules/express/lib/router/index.js:315:13)
    at /home/kd/Documents/GLUU/gluu-passport/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/kd/Documents/GLUU/gluu-passport/node_modules/express/lib/router/index.js:335:12)
    at next (/home/kd/Documents/GLUU/gluu-passport/node_modules/express/lib/router/index.js:275:10)
    at /home/kd/Documents/GLUU/gluu-passport/node_modules/express/lib/router/index.js:635:15
    at next (/home/kd/Documents/GLUU/gluu-passport/node_modules/express/lib/router/index.js:260:14)
    at next (/home/kd/Documents/GLUU/gluu-passport/node_modules/express/lib/router/route.js:127:14)
    at Layer.handle_error (/home/kd/Documents/GLUU/gluu-passport/node_modules/express/lib/router/layer.js:67:12)
    at next (/home/kd/Documents/GLUU/gluu-passport/node_modules/express/lib/router/route.js:135:13)
    at AppleStrategy.strategy.error (/home/kd/Documents/GLUU/gluu-passport/node_modules/passport/lib/middleware/authenticate.js:361:9)
    at AppleStrategy.authenticate (/home/kd/Documents/GLUU/gluu-passport/node_modules/@nicokaiser/passport-apple/lib/strategy.js:162:29)
    at attempt (/home/kd/Documents/GLUU/gluu-passport/node_modules/passport/lib/middleware/authenticate.js:366:16)
    at authenticate (/home/kd/Documents/GLUU/gluu-passport/node_modules/passport/lib/middleware/authenticate.js:367:7)
    at authenticateRequestCallback (/home/kd/Documents/GLUU/gluu-passport/server/routes.js:127:4)
    at Layer.handle [as handle_request] (/home/kd/Documents/GLUU/gluu-passport/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/kd/Documents/GLUU/gluu-passport/node_modules/express/lib/router/route.js:137:13)
    at urlencodedParser (/home/kd/Documents/GLUU/gluu-passport/node_modules/body-parser/lib/types/urlencoded.js:82:7)
    at Layer.handle [as handle_request] (/home/kd/Documents/GLUU/gluu-passport/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/kd/Documents/GLUU/gluu-passport/node_modules/express/lib/router/route.js:137:13)
cTypeError: Cannot read property 'location' of undefined
    at redirect (/home/kd/Documents/GLUU/gluu-passport/node_modules/express/lib/response.js:926:18)
    at /home/kd/Documents/GLUU/gluu-passport/server/app-factory.js:47:7
    at Layer.handle_error (/home/kd/Documents/GLUU/gluu-passport/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/home/kd/Documents/GLUU/gluu-passport/node_modules/express/lib/router/index.js:315:13)
    at /home/kd/Documents/GLUU/gluu-passport/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/kd/Documents/GLUU/gluu-passport/node_modules/express/lib/router/index.js:335:12)
    at next (/home/kd/Documents/GLUU/gluu-passport/node_modules/express/lib/router/index.js:275:10)
    at /home/kd/Documents/GLUU/gluu-passport/node_modules/express/lib/router/index.js:635:15
    at next (/home/kd/Documents/GLUU/gluu-passport/node_modules/express/lib/router/index.js:260:14)
    at next (/home/kd/Documents/GLUU/gluu-passport/node_modules/express/lib/router/route.js:127:14)
    at Layer.handle_error (/home/kd/Documents/GLUU/gluu-passport/node_modules/express/lib/router/layer.js:67:12)
    at next (/home/kd/Documents/GLUU/gluu-passport/node_modules/express/lib/router/route.js:135:13)
    at Layer.handle [as handle_request] (/home/kd/Documents/GLUU/gluu-passport/node_modules/express/lib/router/layer.js:97:5)
    at next (/home/kd/Documents/GLUU/gluu-passport/node_modules/express/lib/router/route.js:137:13)
    at urlencodedParser (/home/kd/Documents/GLUU/gluu-passport/node_modules/body-parser/lib/types/urlencoded.js:82:7)
    at Layer.handle [as handle_request] (/home/kd/Documents/GLUU/gluu-passport/node_modules/express/lib/router/layer.js:95:5)
```

How to reproduce
1. configure any providers for example: `passport-openidconnect`
2. request for passport social and select external op
3. login into external op and deny consent(on consent screen deny the consent)
4. external op will redirect back to passport with `access_denied` error
5. now here is passport throwing this error

Solution:
1. Code is failing here https://github.com/GluuFederation/gluu-passport/blob/master/server/app-factory.js#L42 and https://github.com/GluuFederation/gluu-passport/blob/master/server/app-factory.js#L45
2. Code Destructuring concept is failing in response object case so we need to update this code like below and use `res.redirect` instead of Destructuring
```
app.use((err, req, res, next) => {
      logger.log2('error', `Unknown Error: ${err}`)
      logger.log2('error', err.stack)
      res.redirect(
    `${global.basicConfig.failureRedirectUrl}?failure=An error occurred`
      )
    })
```

### LINKED ISSUE #173: TypeError: req.flash is not a function in apple inbound-auth
Support issue 9097

```
2020-11-27T12:05:49.745Z [ERROR]    Unknown Error: TypeError: req.flash is not a function
2020-11-27T12:05:49.745Z [ERROR]    TypeError: req.flash is not a function
    at allFailed (/home/Documents/GLUU/gluu-passport/node_modules/passport/lib/middleware/authenticate.js:131:15)
    at attempt (/home/Documents/GLUU/gluu-passport/node_modules/passport/lib/middleware/authenticate.js:180:28)
    at AppleStrategy.strategy.fail (/home/Documents/GLUU/gluu-passport/node_modules/passport/lib/middleware/authenticate.js:302:9)
    at AppleStrategy.authenticate (/home/Documents/GLUU/gluu-passport/node_modules/@nicokaiser/passport-apple/lib/strategy.js:70:29)
    at attempt (/home/Documents/GLUU/gluu-passport/node_modules/passport/lib/middleware/authenticate.js:366:16)
    at authenticate (/home/Documents/GLUU/gluu-passport/node_modules/passport/lib/middleware/authenticate.js:367:7)
    at authenticateRequestCallback (/home/Documents/GLUU/gluu-passport/server/routes.js:127:4)
    at Layer.handle [as handle_request] (/home/Documents/GLUU/gluu-passport/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/Documents/GLUU/gluu-passport/node_modules/express/lib/router/route.js:137:13)
    at urlencodedParser (/home/Documents/GLUU/gluu-passport/node_modules/body-parser/lib/types/urlencoded.js:82:7)
    at Layer.handle [as handle_request] (/home/Documents/GLUU/gluu-passport/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/Documents/GLUU/gluu-passport/node_modules/express/lib/router/route.js:137:13)
    at validateProvider (/home/Documents/GLUU/gluu-passport/server/routes.js:98:5)
    at Layer.handle [as handle_request] (/home/Documents/GLUU/gluu-passport/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/Documents/GLUU/gluu-passport/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/Documents/GLUU/gluu-passport/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/Documents/GLUU/gluu-passport/node_modules/express/lib/router/layer.js:95:5)
    at /home/Documents/GLUU/gluu-passport/node_modules/express/lib/router/index.js:281:22
    at param (/home/Documents/GLUU/gluu-passport/node_modules/express/lib/router/index.js:354:14)
    at param (/home/Documents/GLUU/gluu-passport/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/home/Documents/GLUU/gluu-passport/node_modules/express/lib/router/index.js:410:3)
    at next (/home/Documents/GLUU/gluu-passport/node_modules/express/lib/router/index.js:275:10)

```

How to reproduce:

1. Add apple provider
1. Enable passport-social
1. Try to login with apple and **deny apple consent**
1. when we get back to passport after apple auth, passport throwing above error

Solution
1. Need to use and add middleware to use flash https://github.com/jaredhanson/connect-flash

### PR DESCRIPTION
**Pull request by kdhttps**
closes #170
closes #173

### CODE REVIEW

**Comment by christian-hawk** [comment]
Can one of the admins verify this patch?

**Comment by christian-hawk** [comment]
run tests

**Comment by christian-hawk** [comment]
run tests

**Comment by christian-hawk** [comment]
run tests

**Comment by kdhttps** [comment]
@christian-hawk mate, could you please review this PR? we need to add this fix in 4.2.2

**Review by christian-hawk — APPROVED** [review]
Yeah man! Perfect.

**Comment by christian-hawk** [comment]
run tests

**Comment by christian-hawk** [comment]
run tests

**Pull request merged**
