### PR TITLE
Log Strategy fail messages

### LINKED ISSUE #250: Track and log req.flash strategy error message return by passport strategies
## Expected behavior

gluu-passport should show/log the error message thrown by passport strategies when it fails.

## Actual behavior

gluu-passport is not logging/presenting error message when strategy fail/error.

For example: If passport strategy fails to get token or state verification then it storing this error message in `req.flash` but as per current code, we just directly redirecting user to login page and no track why auth/strategy is failing.

## How to reproduce
1. Configure any one provider
2. try to login with provider
3. deny consent at external provider so that gluu-passport fails
4. now here we just redirected to login page and no track why auth is failing

### PR DESCRIPTION
**Pull request by kdhttps**
close #250

### CODE REVIEW

**Comment by christian-hawk** [comment]
run tests

**Review by christian-hawk — COMMENTED** [review]
- error logger should be called on `StrategyError` (when calls globalErrorHandling) (super Error -> globalErrorHandling), not on error handling.

- you can also use `this.name = this.constructor.name`


### Suggestions:

Custom Error Integration test
```js
it('should call globalErrorHandler with correct error message', () => {
	
	const errorMessage = "A valid strategy error message"
	const expectedMessage = `StrategyError: ${errorMessage}`
	// call error inside express, maybe with handleStrategyError? (see last lines...)
	sinon.assert.calledWith(globalErrorHandlerSpy, sinon.match("err", expectedMessage))

} )
````

```js
class StrategyError extends Error {
   constructor (message = 'Strategy Error') {
     super(`StrategyError: ${message}`)
     this.name = 'StrategyError'
   }
 }
````



Feature (function) (req.flash throws error) unit test: 
```js
it ('should throw StrategyError with req.flash message', () => {
	const errorMessage = "A valid strategy error message"
	
	expect(
		handleStrategyError(
			mockedRequest(), // .flash = errorMessage
			mockedResponse()
			)
		.to.throw(StrategyError)
		)
	expect(
		handleStrategyError(
			mockedRequest(), // .flash = errorMessage
			mockedResponse()
			)
		).to.throw(errorMessage)

})

// implement handleStrategyError function


```

- Unit
	- Test if `StrategyError` extends `Error`


- Need to create tests in case /error endpoint is called **without** `req.flash`.

**Comment by kdhttps** [comment]
@christian-hawk mate, could you please review PR? push review changes, only one thing is remain
not able to spy on `globalErrorHandler`, [here is code](https://github.com/GluuFederation/gluu-passport/blob/7b5e97e4bbc8c28e7628ec2797d2e4a9ce0341bb/test/error-handler.spec.js#L21), if you have any suggestion please let me know?
```
it('should call globalErrorHandler with correct error message', () => {	
	const errorMessage = "A valid strategy error message"
	const expectedMessage = `StrategyError: ${errorMessage}`
	// call error inside express, maybe with handleStrategyError? (see last lines...)
	sinon.assert.calledWith(globalErrorHandlerSpy, sinon.match("err", expectedMessage))
} )
```

**Review by christian-hawk — CHANGES_REQUESTED** [review]
@kdhttps please resolve conflicts so I can merge.

**Comment by kdhttps** [comment]
Fixed mate, about integration test for error-handler, i think we don’t need to write `test/error-handler.spec.js` because we already covered integration test on `routes.spec.js`. let me know mate, what you suggest?

**Review by christian-hawk — APPROVED** [review]

**Pull request merged**
