### PR TITLE
fix(dependencies): relock file to fix vulnerability

### PR DESCRIPTION
**Pull request by christian-hawk**
Fix underscore vunlerability and update other deps

### CODE REVIEW

**Comment by christian-hawk** [comment]
run tests

**Comment by christian-hawk** [comment]
run tests

**Comment by christian-hawk** [comment]
run tests

**Comment by christian-hawk** [comment]
run tests

**Comment by christian-hawk** [comment]
run tests

**Comment by christian-hawk** [comment]
run tests

**Comment by christian-hawk** [comment]
run tests

**Review by kdhttps — APPROVED** [review]

**Pull request merged**
