### PR TITLE
test: separate unit and integration tests

### LINKED ISSUE #148: passport-saml outdated
passport-saml released major version. We should update accordingly, need to adapt to breaking changes if they exist.

### LINKED ISSUE #184: Unit and integration tests are together
Unit tests and (complex) integration tests (like testing the passport configuration flow) are run together.

Today what happens:

1. Mocked configuration endpoints are exposed
2. Passport starts (mocked configuration takes place)
3. Tests run

This was made when passport had zero tests.

Now with more coverage, this is becoming a problem. Somehow we cannot clean values from memory even restarting the server programatically, so this started to be a **blocker** for unit tests. If we need to test an unit that is loaded, I have no way to restart/mock/stub.

My suggestion is to **separate integration tests and unit tests**, and also **"merge" the coverage report**.

We can use one of the following:

| convention | unit | integration |
|---|---|---|
| filename | `*.test.js` | `*.spec.js` |
| path | `/test/unit` | `/test/integration` |

Using the first one is easier to handle, setup tests and ci.
Using the second one is more clean and clear.

### PR DESCRIPTION
**Pull request by christian-hawk**
fix #184 

- [x] Setup unit and integration tests
- [x] Separate unit and integration tests
- [x] Merge code coverage report
- [x] Update CI jobs (github actions)

### CODE REVIEW

**Comment by christian-hawk** [comment]
run tests

**Review by kdhttps — APPROVED** [review]
Indeed! Thanks @christian-hawk friend! Excellent Job :clap:

**Comment by kdhttps** [comment]
@christian-hawk Mate, Jenkins-104 test is failing, is it ok or not? can we merge this PR?

**Comment by kdhttps** [comment]
run tests

**Comment by kdhttps** [comment]
Can one of the admins verify this patch?

**Comment by kdhttps** [comment]
run tests

**Comment by kdhttps** [comment]
run tests

**Comment by christian-hawk** [comment]
run tests

**Comment by christian-hawk** [comment]
run tests

**Pull request merged**
